# Generated by Django 4.0.2 on 2024-07-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='visit_count',
            field=models.IntegerField(default=0),
        ),
    ]
