# Generated by Django 4.0.2 on 2024-07-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_url_visit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
